server:
  port: 9210
spring:
  application:
    name: seata-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.68.134:8848
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://192.168.68.134:3306/seata_order?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

